const question = {
  result: {
    id: 'SV_00yj1isZH9WGeDY',
    name: 'Questionnaire Survey',
    ownerId: 'UR_33199b79929a4ec',
    organizationId: 'cpfrhstest',
    isActive: true,
    creationDate: '2024-03-12T10:25:10Z',
    lastModifiedDate: '2024-03-13T10:45:12Z',
    expiration: {
      startDate: null,
      endDate: null,
    },
    questions: {
      QID1: {
        questionType: {
          type: 'DB',
          selector: 'TB',
          subSelector: null,
        },
        questionText:
          '<strong>Contact info:</strong><br />\n - Name: ${e://Field/Name}<br />\n - Email: ${e://Field/ContactEmail}<br />\n - Spouse Email: ${e://Field/Spouse%20Email}<br />\n - Type: ${e://Field/Type}<br />\n<strong>Interview info:</strong><br />\n - Name: ${e://Field/Interviewer}<br />\n - Email: ${e://Field/Interviewer%20Email}<br />\n<strong>Store:</strong><br />\n - Store name: ${e://Field/Store%20Name}<br />\n - State: ${e://Field/State}',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q1',
      },
      QID2: {
        questionType: {
          type: 'MC',
          selector: 'SAVR',
          subSelector: 'TX',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q2',
        choices: {
          1: {
            recode: '1',
            description: '1',
            choiceText: '1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: '2',
            choiceText: '2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: '3',
            choiceText: '3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID23: {
        questionType: {
          type: 'MC',
          selector: 'MAVR',
          subSelector: 'TX',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q3',
        choices: {
          1: {
            recode: '1',
            description: '1A',
            choiceText: '1A',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: '1B',
            choiceText: '1B',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: '1C',
            choiceText: '1C',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID3: {
        questionType: {
          type: 'TE',
          selector: 'AUTO',
          subSelector: 'SDS',
        },
        questionText: 'City',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q4',
      },
      QID25: {
        questionType: {
          type: 'TE',
          selector: 'ML',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q5',
      },
      QID26: {
        questionType: {
          type: 'TE',
          selector: 'ESTB',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q6',
      },
      QID27: {
        questionType: {
          type: 'TE',
          selector: 'PW',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q7',
      },
      QID4: {
        questionType: {
          type: 'DB',
          selector: 'TB',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q8',
      },
      QID28: {
        questionType: {
          type: 'DB',
          selector: 'GRB',
          subSelector: 'WTXB',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q9',
      },
      QID29: {
        questionType: {
          type: 'DB',
          selector: 'FLB',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q10',
      },
      QID5: {
        questionType: {
          type: 'Matrix',
          selector: 'Likert',
          subSelector: 'SingleAnswer',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q11',
        subQuestions: {
          1: {
            recode: '1',
            description: 'Click to write Statement 1:Right',
            choiceText: 'Click to write Statement 1:Right',
            variableName: null,
            imageDescription: null,
          },
          2: {
            recode: '2',
            description: 'Click to write Statement 2:Right',
            choiceText: 'Click to write Statement 2:Right',
            variableName: null,
            imageDescription: null,
          },
        },
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Scale Point 1',
            choiceText: 'Click to write Scale Point 1',
            imageDescription: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Scale Point 2',
            choiceText: 'Click to write Scale Point 2',
            imageDescription: null,
            analyze: true,
          },
        },
      },
      QID30: {
        questionType: {
          type: 'Matrix',
          selector: 'Bipolar',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q12',
        subQuestions: {
          1: {
            recode: '1',
            description: 'Click to write Statement 1:Right',
            choiceText: 'Click to write Statement 1:Right',
            variableName: null,
            imageDescription: null,
          },
          2: {
            recode: '2',
            description: 'Click to write Statement 2:Right',
            choiceText: 'Click to write Statement 2:Right',
            variableName: null,
            imageDescription: null,
          },
          3: {
            recode: '3',
            description: 'Click to write Statement 3:Right',
            choiceText: 'Click to write Statement 3:Right',
            variableName: null,
            imageDescription: null,
          },
        },
        choices: {
          1: {
            recode: '1',
            description: '1',
            choiceText: '1',
            imageDescription: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: '2',
            choiceText: '2',
            imageDescription: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: '3',
            choiceText: '3',
            imageDescription: null,
            analyze: true,
          },
        },
      },
      QID31: {
        questionType: {
          type: 'Matrix',
          selector: 'RO',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q13',
        subQuestions: {
          1: {
            recode: '1',
            description: 'Click to write Statement 1',
            choiceText: 'Click to write Statement 1',
            variableName: null,
            imageDescription: null,
          },
          2: {
            recode: '2',
            description: 'Click to write Statement 2',
            choiceText: 'Click to write Statement 2',
            variableName: null,
            imageDescription: null,
          },
          3: {
            recode: '3',
            description: 'Click to write Statement 3',
            choiceText: 'Click to write Statement 3',
            variableName: null,
            imageDescription: null,
          },
        },
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Scale Point 1',
            choiceText: 'Click to write Scale Point 1',
            imageDescription: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Scale Point 2',
            choiceText: 'Click to write Scale Point 2',
            imageDescription: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Scale Point 3',
            choiceText: 'Click to write Scale Point 3',
            imageDescription: null,
            analyze: true,
          },
        },
      },
      QID32: {
        questionType: {
          type: 'Matrix',
          selector: 'CS',
          subSelector: 'WTB',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q14',
        subQuestions: {
          1: {
            recode: '1',
            description: 'Click to write Statement 1',
            choiceText: 'Click to write Statement 1',
            variableName: null,
            imageDescription: null,
          },
          2: {
            recode: '2',
            description: 'Click to write Statement 2',
            choiceText: 'Click to write Statement 2',
            variableName: null,
            imageDescription: null,
          },
          3: {
            recode: '3',
            description: 'Click to write Statement 3',
            choiceText: 'Click to write Statement 3',
            variableName: null,
            imageDescription: null,
          },
        },
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Scale Point 1',
            choiceText: 'Click to write Scale Point 1',
            imageDescription: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Scale Point 2',
            choiceText: 'Click to write Scale Point 2',
            imageDescription: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Scale Point 3',
            choiceText: 'Click to write Scale Point 3',
            imageDescription: null,
            analyze: true,
          },
        },
      },
      QID33: {
        questionType: {
          type: 'Matrix',
          selector: 'TE',
          subSelector: 'Short',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q15',
        subQuestions: {
          1: {
            recode: '1',
            description: 'Click to write Statement 1',
            choiceText: 'Click to write Statement 1',
            variableName: null,
            imageDescription: null,
          },
          2: {
            recode: '2',
            description: 'Click to write Statement 2',
            choiceText: 'Click to write Statement 2',
            variableName: null,
            imageDescription: null,
          },
          3: {
            recode: '3',
            description: 'Click to write Statement 3',
            choiceText: 'Click to write Statement 3',
            variableName: null,
            imageDescription: null,
          },
        },
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Scale Point 1',
            choiceText: 'Click to write Scale Point 1',
            imageDescription: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Scale Point 2',
            choiceText: 'Click to write Scale Point 2',
            imageDescription: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Scale Point 3',
            choiceText: 'Click to write Scale Point 3',
            imageDescription: null,
            analyze: true,
          },
        },
      },
      QID34: {
        questionType: {
          type: 'Matrix',
          selector: 'MaxDiff',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q16',
        subQuestions: {
          1: {
            recode: '1',
            description: 'Click to write Statement 1',
            choiceText: 'Click to write Statement 1',
            variableName: null,
            imageDescription: null,
          },
          2: {
            recode: '2',
            description: 'Click to write Statement 2',
            choiceText: 'Click to write Statement 2',
            variableName: null,
            imageDescription: null,
          },
          3: {
            recode: '3',
            description: 'Click to write Statement 3',
            choiceText: 'Click to write Statement 3',
            variableName: null,
            imageDescription: null,
          },
        },
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Scale Point 1',
            choiceText: 'Click to write Scale Point 1',
            imageDescription: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Scale Point 2',
            choiceText: 'Click to write Scale Point 2',
            imageDescription: null,
            analyze: true,
          },
        },
      },
      QID6: {
        questionType: {
          type: 'Slider',
          selector: 'HSLIDER',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q17',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Choice 1',
            choiceText: 'Click to write Choice 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Choice 2',
            choiceText: 'Click to write Choice 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Choice 3',
            choiceText: 'Click to write Choice 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID35: {
        questionType: {
          type: 'Slider',
          selector: 'HBAR',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q18',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Choice 1',
            choiceText: 'Click to write Choice 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Choice 2',
            choiceText: 'Click to write Choice 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Choice 3',
            choiceText: 'Click to write Choice 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID36: {
        questionType: {
          type: 'Slider',
          selector: 'STAR',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q19',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Choice 1',
            choiceText: 'Click to write Choice 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Choice 2',
            choiceText: 'Click to write Choice 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Choice 3',
            choiceText: 'Click to write Choice 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID7: {
        questionType: {
          type: 'TE',
          selector: 'FORM',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q20',
        choices: {
          1: {
            description: 'Click to write Choice 1',
            choiceText: 'Click to write Choice 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            description: 'Click to write Choice 2',
            choiceText: 'Click to write Choice 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            description: 'Click to write Choice 3',
            choiceText: 'Click to write Choice 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID8: {
        questionType: {
          type: 'RO',
          selector: 'DND',
          subSelector: 'TX',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q21',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Item 1',
            choiceText: 'Click to write Item 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Item 2',
            choiceText: 'Click to write Item 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Item 3',
            choiceText: 'Click to write Item 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID37: {
        questionType: {
          type: 'RO',
          selector: 'RB',
          subSelector: 'TX',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q22',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Item 1',
            choiceText: 'Click to write Item 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Item 2',
            choiceText: 'Click to write Item 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Item 3',
            choiceText: 'Click to write Item 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID38: {
        questionType: {
          type: 'RO',
          selector: 'VR',
          subSelector: 'TX',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q23',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Item 1',
            choiceText: 'Click to write Item 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Item 2',
            choiceText: 'Click to write Item 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Item 3',
            choiceText: 'Click to write Item 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID39: {
        questionType: {
          type: 'RO',
          selector: 'SB',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q24',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Item 1',
            choiceText: 'Click to write Item 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Item 2',
            choiceText: 'Click to write Item 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Item 3',
            choiceText: 'Click to write Item 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID9: {
        questionType: {
          type: 'SBS',
          selector: 'SBSMatrix',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        questionName: 'Q25',
        validation: {
          doesForceResponse: false,
        },
        columns: {
          1: {
            questionType: {
              type: 'Matrix',
              selector: 'Likert',
              subSelector: 'SingleAnswer',
            },
            questionText: 'Click to write Column 1',
            questionLabel: null,
            validation: {
              doesForceResponse: false,
            },
            choices: {
              1: {
                recode: '1',
                description: 'Answer 1',
                choiceText: 'Answer 1',
                imageDescription: null,
                analyze: true,
              },
              2: {
                recode: '2',
                description: 'Answer 2',
                choiceText: 'Answer 2',
                imageDescription: null,
                analyze: true,
              },
            },
          },
          2: {
            questionType: {
              type: 'Matrix',
              selector: 'Likert',
              subSelector: 'SingleAnswer',
            },
            questionText: 'Click to write Column 2',
            questionLabel: null,
            validation: {
              doesForceResponse: false,
            },
            choices: {
              1: {
                recode: '1',
                description: 'Answer 1',
                choiceText: 'Answer 1',
                imageDescription: null,
                analyze: true,
              },
              2: {
                recode: '2',
                description: 'Answer 2',
                choiceText: 'Answer 2',
                imageDescription: null,
                analyze: true,
              },
            },
          },
        },
        subQuestions: {
          1: {
            recode: '1',
            description: 'Click to write Statement 1',
            choiceText: 'Click to write Statement 1',
            variableName: null,
            imageDescription: null,
          },
          2: {
            recode: '2',
            description: 'Click to write Statement 2',
            choiceText: 'Click to write Statement 2',
            variableName: null,
            imageDescription: null,
          },
          3: {
            recode: '3',
            description: 'Click to write Statement 3',
            choiceText: 'Click to write Statement 3',
            variableName: null,
            imageDescription: null,
          },
        },
      },
      QID10: {
        questionType: {
          type: 'MC',
          selector: 'NPS',
          subSelector: null,
        },
        questionText:
          'How likely are you to recommend [INSERT COMPANY NAME HERE] to a friend or colleague?',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q26',
        choices: {
          0: {
            recode: '0',
            description: '0',
            choiceText: '0',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          1: {
            recode: '1',
            description: '1',
            choiceText: '1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: '2',
            choiceText: '2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: '3',
            choiceText: '3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          4: {
            recode: '4',
            description: '4',
            choiceText: '4',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          5: {
            recode: '5',
            description: '5',
            choiceText: '5',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          6: {
            recode: '6',
            description: '6',
            choiceText: '6',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          7: {
            recode: '7',
            description: '7',
            choiceText: '7',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          8: {
            recode: '8',
            description: '8',
            choiceText: '8',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          9: {
            recode: '9',
            description: '9',
            choiceText: '9',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          10: {
            recode: '10',
            description: '10',
            choiceText: '10',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID11: {
        questionType: {
          type: 'Timing',
          selector: 'PageTimer',
          subSelector: null,
        },
        questionText: 'Timing',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q27',
        choices: {
          1: {
            recode: '1',
            description: 'First Click',
            choiceText: 'First Click',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Last Click',
            choiceText: 'Last Click',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Page Submit',
            choiceText: 'Page Submit',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          4: {
            recode: '4',
            description: 'Click Count',
            choiceText: 'Click Count',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID12: {
        questionType: {
          type: 'SS',
          selector: 'TA',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q28',
        choices: {
          0: {
            recode: '0',
            description: '0',
            choiceText: '0',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          1: {
            recode: '1',
            description: '1',
            choiceText: '1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: '2',
            choiceText: '2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: '3',
            choiceText: '3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          4: {
            recode: '4',
            description: '4',
            choiceText: '4',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          5: {
            recode: '5',
            description: '5',
            choiceText: '5',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          6: {
            recode: '6',
            description: '6',
            choiceText: '6',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          7: {
            recode: '7',
            description: '7',
            choiceText: '7',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          8: {
            recode: '8',
            description: '8',
            choiceText: '8',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          9: {
            recode: '9',
            description: '9',
            choiceText: '9',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          10: {
            recode: '10',
            description: '10',
            choiceText: '10',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          11: {
            recode: '11',
            description: '11',
            choiceText: '11',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          12: {
            recode: '12',
            description: '12',
            choiceText: '12',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          13: {
            recode: '13',
            description: '13',
            choiceText: '13',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID13: {
        questionType: {
          type: 'CS',
          selector: 'VRTL',
          subSelector: 'TX',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q29',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Choice 1',
            choiceText: 'Click to write Choice 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Choice 2',
            choiceText: 'Click to write Choice 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Choice 3',
            choiceText: 'Click to write Choice 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID40: {
        questionType: {
          type: 'CS',
          selector: 'HBAR',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q30',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Choice 1',
            choiceText: 'Click to write Choice 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Choice 2',
            choiceText: 'Click to write Choice 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Choice 3',
            choiceText: 'Click to write Choice 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID41: {
        questionType: {
          type: 'CS',
          selector: 'HSLIDER',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q31',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Choice 1',
            choiceText: 'Click to write Choice 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Choice 2',
            choiceText: 'Click to write Choice 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Choice 3',
            choiceText: 'Click to write Choice 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID14: {
        questionType: {
          type: 'FileUpload',
          selector: 'FileUpload',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q32',
      },
      QID15: {
        questionType: {
          type: 'PGR',
          selector: 'DragAndDrop',
          subSelector: 'NoColumns',
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        questionName: 'Q33',
        validation: {
          doesForceResponse: false,
        },
        items: {
          1: {
            description: 'Click to write Item 1',
            imageDescription: null,
            analyze: true,
          },
          2: {
            description: 'Click to write Item 2',
            imageDescription: null,
            analyze: true,
          },
          3: {
            description: 'Click to write Item 3',
            imageDescription: null,
            analyze: true,
          },
        },
        groups: {
          0: {
            recode: '0',
            description: 'Click to write Group 1',
          },
          1: {
            recode: '1',
            description: 'Click to write Group 2',
          },
          2: {
            recode: '2',
            description: 'Click to write Group 3',
          },
        },
      },
      QID16: {
        questionType: {
          type: 'DD',
          selector: 'DL',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q34',
        choices: {
          1: {
            recode: '1',
            description: 'Click to write Group 1',
            choiceText: 'Click to write Group 1',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Click to write Group 2',
            choiceText: 'Click to write Group 2',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Click to write Group 3',
            choiceText: 'Click to write Group 3',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID17: {
        questionType: {
          type: 'Draw',
          selector: 'Signature',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q35',
      },
      QID18: {
        questionType: {
          type: 'HeatMap',
          selector: 'Image',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        questionName: 'Q36',
        validation: {
          doesForceResponse: false,
        },
        regions: {
          0: {
            description: 'Region #1',
          },
          1: {
            description: 'Region #2',
          },
          2: {
            description: 'Region #3',
          },
          3: {
            description: 'Region #4',
          },
          4: {
            description: 'Region #5',
          },
        },
      },
      QID19: {
        questionType: {
          type: 'HotSpot',
          selector: 'OnOff',
          subSelector: null,
        },
        questionText: 'Hotpot',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q38',
        subQuestions: {
          1: {
            recode: '1',
            description: '$20 or less',
            choiceText: '$20 or less',
            variableName: null,
            imageDescription: null,
          },
          3: {
            recode: '3',
            description: 'Over $20 to $40',
            choiceText: 'Over $20 to $40',
            variableName: null,
            imageDescription: null,
          },
          4: {
            recode: '4',
            description: 'Over $40 to $60',
            choiceText: 'Over $40 to $60',
            variableName: null,
            imageDescription: null,
          },
          5: {
            recode: '5',
            description: 'Over $60 to $80',
            choiceText: 'Over $60 to $80',
            variableName: null,
            imageDescription: null,
          },
          6: {
            recode: '6',
            description: 'Over $80 to $100',
            choiceText: 'Over $80 to $100',
            variableName: null,
            imageDescription: null,
          },
          7: {
            recode: '7',
            description: 'Over $100',
            choiceText: 'Over $100',
            variableName: null,
            imageDescription: null,
          },
        },
        choices: {
          1: {
            recode: '1',
            description: 'Off',
            choiceText: 'Off',
            imageDescription: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'On',
            choiceText: 'On',
            imageDescription: null,
            analyze: true,
          },
        },
      },
      QID42: {
        questionType: {
          type: 'MC',
          selector: 'SAVR',
          subSelector: 'TX',
        },
        questionText: 'Do you want to skip hot pot question?',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
          type: 'CustomValidation',
        },
        questionName: 'Q37',
        choices: {
          1: {
            recode: '1',
            description: 'Skip',
            choiceText: 'Skip',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID20: {
        questionType: {
          type: 'Meta',
          selector: 'Browser',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q39',
        choices: {
          1: {
            description: 'Browser',
            choiceText: 'Browser',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          2: {
            description: 'Version',
            choiceText: 'Version',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          3: {
            description: 'Operating System',
            choiceText: 'Operating System',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          4: {
            description: 'Screen Resolution',
            choiceText: 'Screen Resolution',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          5: {
            description: 'Flash Version',
            choiceText: 'Flash Version',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          6: {
            description: 'Java Support',
            choiceText: 'Java Support',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
          7: {
            description: 'User Agent',
            choiceText: 'User Agent',
            imageDescription: null,
            variableName: null,
            analyze: true,
          },
        },
      },
      QID21: {
        questionType: {
          type: 'Captcha',
          selector: 'V2',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q40',
      },
      QID22: {
        questionType: {
          type: 'HL',
          selector: 'Text',
          subSelector: null,
        },
        questionText: 'Click to write the question text',
        questionLabel: null,
        validation: {
          doesForceResponse: false,
        },
        questionName: 'Q41',
        subQuestions: {
          4: {
            recode: '4',
            description: '1: This',
            choiceText: '1: This',
            variableName: null,
            imageDescription: null,
          },
          5: {
            recode: '5',
            description: '2: is',
            choiceText: '2: is',
            variableName: null,
            imageDescription: null,
          },
          6: {
            recode: '6',
            description: '3: the',
            choiceText: '3: the',
            variableName: null,
            imageDescription: null,
          },
          7: {
            recode: '7',
            description: '4: text',
            choiceText: '4: text',
            variableName: null,
            imageDescription: null,
          },
          8: {
            recode: '8',
            description: '5: you',
            choiceText: '5: you',
            variableName: null,
            imageDescription: null,
          },
          9: {
            recode: '9',
            description: '6: can',
            choiceText: '6: can',
            variableName: null,
            imageDescription: null,
          },
          10: {
            recode: '10',
            description: '7: highlight',
            choiceText: '7: highlight',
            variableName: null,
            imageDescription: null,
          },
          11: {
            recode: '11',
            description: '8: with',
            choiceText: '8: with',
            variableName: null,
            imageDescription: null,
          },
          12: {
            recode: '12',
            description: '9: the',
            choiceText: '9: the',
            variableName: null,
            imageDescription: null,
          },
          13: {
            recode: '13',
            description: '10: above',
            choiceText: '10: above',
            variableName: null,
            imageDescription: null,
          },
          14: {
            recode: '14',
            description: '11: colour',
            choiceText: '11: colour',
            variableName: null,
            imageDescription: null,
          },
          15: {
            recode: '15',
            description: '12: categories.',
            choiceText: '12: categories.',
            variableName: null,
            imageDescription: null,
          },
          16: {
            recode: '16',
            description: '13: To',
            choiceText: '13: To',
            variableName: null,
            imageDescription: null,
          },
          17: {
            recode: '17',
            description: '14: edit',
            choiceText: '14: edit',
            variableName: null,
            imageDescription: null,
          },
          18: {
            recode: '18',
            description: '15: this',
            choiceText: '15: this',
            variableName: null,
            imageDescription: null,
          },
          19: {
            recode: '19',
            description: '16: text,',
            choiceText: '16: text,',
            variableName: null,
            imageDescription: null,
          },
          20: {
            recode: '20',
            description: '17: click',
            choiceText: '17: click',
            variableName: null,
            imageDescription: null,
          },
          21: {
            recode: '21',
            description: '18: on',
            choiceText: '18: on',
            variableName: null,
            imageDescription: null,
          },
          22: {
            recode: '22',
            description: '19: the',
            choiceText: '19: the',
            variableName: null,
            imageDescription: null,
          },
          23: {
            recode: '23',
            description: '20: link',
            choiceText: '20: link',
            variableName: null,
            imageDescription: null,
          },
          24: {
            recode: '24',
            description: '21: below.',
            choiceText: '21: below.',
            variableName: null,
            imageDescription: null,
          },
          25: {
            recode: '25',
            description: '22: Click',
            choiceText: '22: Click',
            variableName: null,
            imageDescription: null,
          },
          26: {
            recode: '26',
            description: '23: between',
            choiceText: '23: between',
            variableName: null,
            imageDescription: null,
          },
          27: {
            recode: '27',
            description: '24: the',
            choiceText: '24: the',
            variableName: null,
            imageDescription: null,
          },
          28: {
            recode: '28',
            description: '25: words',
            choiceText: '25: words',
            variableName: null,
            imageDescription: null,
          },
          29: {
            recode: '29',
            description: '26: to',
            choiceText: '26: to',
            variableName: null,
            imageDescription: null,
          },
          30: {
            recode: '30',
            description: '27: combine',
            choiceText: '27: combine',
            variableName: null,
            imageDescription: null,
          },
          31: {
            recode: '31',
            description: '28: or',
            choiceText: '28: or',
            variableName: null,
            imageDescription: null,
          },
          32: {
            recode: '32',
            description: '29: separate',
            choiceText: '29: separate',
            variableName: null,
            imageDescription: null,
          },
          33: {
            recode: '33',
            description: '30: them.',
            choiceText: '30: them.',
            variableName: null,
            imageDescription: null,
          },
          34: {
            recode: '34',
            description: '31: Clicking',
            choiceText: '31: Clicking',
            variableName: null,
            imageDescription: null,
          },
          35: {
            recode: '35',
            description: '32: directly',
            choiceText: '32: directly',
            variableName: null,
            imageDescription: null,
          },
          36: {
            recode: '36',
            description: '33: on',
            choiceText: '33: on',
            variableName: null,
            imageDescription: null,
          },
          37: {
            recode: '37',
            description: '34: words',
            choiceText: '34: words',
            variableName: null,
            imageDescription: null,
          },
          38: {
            recode: '38',
            description: '35: will',
            choiceText: '35: will',
            variableName: null,
            imageDescription: null,
          },
          39: {
            recode: '39',
            description: '36: allow',
            choiceText: '36: allow',
            variableName: null,
            imageDescription: null,
          },
          40: {
            recode: '40',
            description: '37: or',
            choiceText: '37: or',
            variableName: null,
            imageDescription: null,
          },
          41: {
            recode: '41',
            description: '38: disallow',
            choiceText: '38: disallow',
            variableName: null,
            imageDescription: null,
          },
          42: {
            recode: '42',
            description: '39: respondents',
            choiceText: '39: respondents',
            variableName: null,
            imageDescription: null,
          },
          43: {
            recode: '43',
            description: '40: from',
            choiceText: '40: from',
            variableName: null,
            imageDescription: null,
          },
          44: {
            recode: '44',
            description: '41: highlighting',
            choiceText: '41: highlighting',
            variableName: null,
            imageDescription: null,
          },
          45: {
            recode: '45',
            description: '42: them.',
            choiceText: '42: them.',
            variableName: null,
            imageDescription: null,
          },
        },
        choices: {
          1: {
            recode: '1',
            description: 'Like',
            choiceText: 'Like',
            imageDescription: null,
            analyze: true,
          },
          2: {
            recode: '2',
            description: 'Neither like nor dislike',
            choiceText: 'Neither like nor dislike',
            imageDescription: null,
            analyze: true,
          },
          3: {
            recode: '3',
            description: 'Dislike',
            choiceText: 'Dislike',
            imageDescription: null,
            analyze: true,
          },
        },
      },
    },
    exportColumnMap: {
      Q1: {
        question: 'QID1',
      },
      Q2: {
        question: 'QID2',
      },
      Q3_1: {
        question: 'QID23',
        choice: 'QID23.choices.1',
      },
      Q3_2: {
        question: 'QID23',
        choice: 'QID23.choices.2',
      },
      Q3_3: {
        question: 'QID23',
        choice: 'QID23.choices.3',
      },
      Q4: {
        question: 'QID3',
      },
      Q5: {
        question: 'QID25',
      },
      Q6: {
        question: 'QID26',
      },
      Q7: {
        question: 'QID27',
      },
      Q8: {
        question: 'QID4',
      },
      Q9: {
        question: 'QID28',
      },
      Q10: {
        question: 'QID29',
      },
      Q11_1: {
        question: 'QID5',
        subQuestion: 'QID5.subQuestions.1',
      },
      Q11_2: {
        question: 'QID5',
        subQuestion: 'QID5.subQuestions.2',
      },
      Q12_1: {
        question: 'QID30',
        subQuestion: 'QID30.subQuestions.1',
      },
      Q12_2: {
        question: 'QID30',
        subQuestion: 'QID30.subQuestions.2',
      },
      Q12_3: {
        question: 'QID30',
        subQuestion: 'QID30.subQuestions.3',
      },
      Q13_1_1: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.1',
        choice: 'QID31.choices.1',
      },
      Q13_1_2: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.1',
        choice: 'QID31.choices.2',
      },
      Q13_1_3: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.1',
        choice: 'QID31.choices.3',
      },
      Q13_2_1: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.2',
        choice: 'QID31.choices.1',
      },
      Q13_2_2: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.2',
        choice: 'QID31.choices.2',
      },
      Q13_2_3: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.2',
        choice: 'QID31.choices.3',
      },
      Q13_3_1: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.3',
        choice: 'QID31.choices.1',
      },
      Q13_3_2: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.3',
        choice: 'QID31.choices.2',
      },
      Q13_3_3: {
        question: 'QID31',
        subQuestion: 'QID31.subQuestions.3',
        choice: 'QID31.choices.3',
      },
      Q14_1_1: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.1',
        choice: 'QID32.choices.1',
      },
      Q14_1_2: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.1',
        choice: 'QID32.choices.2',
      },
      Q14_1_3: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.1',
        choice: 'QID32.choices.3',
      },
      Q14_2_1: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.2',
        choice: 'QID32.choices.1',
      },
      Q14_2_2: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.2',
        choice: 'QID32.choices.2',
      },
      Q14_2_3: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.2',
        choice: 'QID32.choices.3',
      },
      Q14_3_1: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.3',
        choice: 'QID32.choices.1',
      },
      Q14_3_2: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.3',
        choice: 'QID32.choices.2',
      },
      Q14_3_3: {
        question: 'QID32',
        subQuestion: 'QID32.subQuestions.3',
        choice: 'QID32.choices.3',
      },
      Q15_1_1_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.1',
        choice: 'QID33.choices.1',
      },
      Q15_1_2_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.1',
        choice: 'QID33.choices.2',
      },
      Q15_1_3_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.1',
        choice: 'QID33.choices.3',
      },
      Q15_2_1_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.2',
        choice: 'QID33.choices.1',
      },
      Q15_2_2_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.2',
        choice: 'QID33.choices.2',
      },
      Q15_2_3_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.2',
        choice: 'QID33.choices.3',
      },
      Q15_3_1_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.3',
        choice: 'QID33.choices.1',
      },
      Q15_3_2_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.3',
        choice: 'QID33.choices.2',
      },
      Q15_3_3_TEXT: {
        question: 'QID33',
        subQuestion: 'QID33.subQuestions.3',
        choice: 'QID33.choices.3',
      },
      Q16_1: {
        question: 'QID34',
        subQuestion: 'QID34.subQuestions.1',
      },
      Q16_2: {
        question: 'QID34',
        subQuestion: 'QID34.subQuestions.2',
      },
      Q16_3: {
        question: 'QID34',
        subQuestion: 'QID34.subQuestions.3',
      },
      Q17_1: {
        question: 'QID6',
        choice: 'QID6.choices.1',
      },
      Q17_2: {
        question: 'QID6',
        choice: 'QID6.choices.2',
      },
      Q17_3: {
        question: 'QID6',
        choice: 'QID6.choices.3',
      },
      Q18_1: {
        question: 'QID35',
        choice: 'QID35.choices.1',
      },
      Q18_2: {
        question: 'QID35',
        choice: 'QID35.choices.2',
      },
      Q18_3: {
        question: 'QID35',
        choice: 'QID35.choices.3',
      },
      Q19_1: {
        question: 'QID36',
        choice: 'QID36.choices.1',
      },
      Q19_2: {
        question: 'QID36',
        choice: 'QID36.choices.2',
      },
      Q19_3: {
        question: 'QID36',
        choice: 'QID36.choices.3',
      },
      Q20_1_TEXT: {
        question: 'QID7',
        choice: 'QID7.choices.1',
      },
      Q20_2_TEXT: {
        question: 'QID7',
        choice: 'QID7.choices.2',
      },
      Q20_3_TEXT: {
        question: 'QID7',
        choice: 'QID7.choices.3',
      },
      Q21_1: {
        question: 'QID8',
        choice: 'QID8.choices.1',
      },
      Q21_2: {
        question: 'QID8',
        choice: 'QID8.choices.2',
      },
      Q21_3: {
        question: 'QID8',
        choice: 'QID8.choices.3',
      },
      Q22_1: {
        question: 'QID37',
        choice: 'QID37.choices.1',
      },
      Q22_2: {
        question: 'QID37',
        choice: 'QID37.choices.2',
      },
      Q22_3: {
        question: 'QID37',
        choice: 'QID37.choices.3',
      },
      Q23_1: {
        question: 'QID38',
        choice: 'QID38.choices.1',
      },
      Q23_2: {
        question: 'QID38',
        choice: 'QID38.choices.2',
      },
      Q23_3: {
        question: 'QID38',
        choice: 'QID38.choices.3',
      },
      Q24_1: {
        question: 'QID39',
        choice: 'QID39.choices.1',
      },
      Q24_2: {
        question: 'QID39',
        choice: 'QID39.choices.2',
      },
      Q24_3: {
        question: 'QID39',
        choice: 'QID39.choices.3',
      },
      'Q25#1_1': {
        question: 'QID9',
        column: 'QID9.columns.1',
        subQuestion: 'QID9.subQuestions.1',
      },
      'Q25#1_2': {
        question: 'QID9',
        column: 'QID9.columns.1',
        subQuestion: 'QID9.subQuestions.2',
      },
      'Q25#1_3': {
        question: 'QID9',
        column: 'QID9.columns.1',
        subQuestion: 'QID9.subQuestions.3',
      },
      'Q25#2_1': {
        question: 'QID9',
        column: 'QID9.columns.2',
        subQuestion: 'QID9.subQuestions.1',
      },
      'Q25#2_2': {
        question: 'QID9',
        column: 'QID9.columns.2',
        subQuestion: 'QID9.subQuestions.2',
      },
      'Q25#2_3': {
        question: 'QID9',
        column: 'QID9.columns.2',
        subQuestion: 'QID9.subQuestions.3',
      },
      Q26: {
        question: 'QID10',
      },
      Q27_1: {
        question: 'QID11',
        choice: 'QID11.choices.1',
      },
      Q27_2: {
        question: 'QID11',
        choice: 'QID11.choices.2',
      },
      Q27_3: {
        question: 'QID11',
        choice: 'QID11.choices.3',
      },
      Q27_4: {
        question: 'QID11',
        choice: 'QID11.choices.4',
      },
      Q28: {
        question: 'QID12',
      },
      Q29_1: {
        question: 'QID13',
        choice: 'QID13.choices.1',
      },
      Q29_2: {
        question: 'QID13',
        choice: 'QID13.choices.2',
      },
      Q29_3: {
        question: 'QID13',
        choice: 'QID13.choices.3',
      },
      Q30_1: {
        question: 'QID40',
        choice: 'QID40.choices.1',
      },
      Q30_2: {
        question: 'QID40',
        choice: 'QID40.choices.2',
      },
      Q30_3: {
        question: 'QID40',
        choice: 'QID40.choices.3',
      },
      Q31_1: {
        question: 'QID41',
        choice: 'QID41.choices.1',
      },
      Q31_2: {
        question: 'QID41',
        choice: 'QID41.choices.2',
      },
      Q31_3: {
        question: 'QID41',
        choice: 'QID41.choices.3',
      },
      Q32_FILE_ID: {
        question: 'QID14',
      },
      Q32_FILE_NAME: {
        question: 'QID14',
      },
      Q32_FILE_SIZE: {
        question: 'QID14',
      },
      Q32_FILE_TYPE: {
        question: 'QID14',
      },
      Q33_1_Group: {
        question: 'QID15',
        item: 'QID15.items.1',
      },
      Q33_1_Rank: {
        question: 'QID15',
        item: 'QID15.items.1',
      },
      Q33_2_Group: {
        question: 'QID15',
        item: 'QID15.items.2',
      },
      Q33_2_Rank: {
        question: 'QID15',
        item: 'QID15.items.2',
      },
      Q33_3_Group: {
        question: 'QID15',
        item: 'QID15.items.3',
      },
      Q33_3_Rank: {
        question: 'QID15',
        item: 'QID15.items.3',
      },
      Q34_1: {
        question: 'QID16',
        subQuestion: 'QID16.subQuestions.1',
      },
      Q34_2: {
        question: 'QID16',
        subQuestion: 'QID16.subQuestions.2',
      },
      Q34_3: {
        question: 'QID16',
        subQuestion: 'QID16.subQuestions.3',
      },
      Q35_FILE_ID: {
        question: 'QID17',
      },
      Q35_FILE_NAME: {
        question: 'QID17',
      },
      Q35_FILE_SIZE: {
        question: 'QID17',
      },
      Q35_FILE_TYPE: {
        question: 'QID17',
      },
      Q36_1_x: {
        question: 'QID18',
      },
      Q36_1_y: {
        question: 'QID18',
      },
      Q36_0: {
        question: 'QID18',
        region: 'QID18.regions.0',
      },
      Q36_1: {
        question: 'QID18',
        region: 'QID18.regions.1',
      },
      Q36_2: {
        question: 'QID18',
        region: 'QID18.regions.2',
      },
      Q36_3: {
        question: 'QID18',
        region: 'QID18.regions.3',
      },
      Q36_4: {
        question: 'QID18',
        region: 'QID18.regions.4',
      },
      Q38_1: {
        question: 'QID19',
        subQuestion: 'QID19.subQuestions.1',
      },
      Q38_3: {
        question: 'QID19',
        subQuestion: 'QID19.subQuestions.3',
      },
      Q38_4: {
        question: 'QID19',
        subQuestion: 'QID19.subQuestions.4',
      },
      Q38_5: {
        question: 'QID19',
        subQuestion: 'QID19.subQuestions.5',
      },
      Q38_6: {
        question: 'QID19',
        subQuestion: 'QID19.subQuestions.6',
      },
      Q38_7: {
        question: 'QID19',
        subQuestion: 'QID19.subQuestions.7',
      },
      Q37: {
        question: 'QID42',
      },
      Q39_1_TEXT: {
        question: 'QID20',
        choice: 'QID20.choices.1',
      },
      Q39_2_TEXT: {
        question: 'QID20',
        choice: 'QID20.choices.2',
      },
      Q39_3_TEXT: {
        question: 'QID20',
        choice: 'QID20.choices.3',
      },
      Q39_4_TEXT: {
        question: 'QID20',
        choice: 'QID20.choices.4',
      },
      Q39_5_TEXT: {
        question: 'QID20',
        choice: 'QID20.choices.5',
      },
      Q39_6_TEXT: {
        question: 'QID20',
        choice: 'QID20.choices.6',
      },
      Q39_7_TEXT: {
        question: 'QID20',
        choice: 'QID20.choices.7',
      },
      Q41_4: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.4',
      },
      Q41_5: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.5',
      },
      Q41_6: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.6',
      },
      Q41_7: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.7',
      },
      Q41_8: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.8',
      },
      Q41_9: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.9',
      },
      Q41_10: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.10',
      },
      Q41_11: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.11',
      },
      Q41_12: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.12',
      },
      Q41_13: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.13',
      },
      Q41_14: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.14',
      },
      Q41_15: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.15',
      },
      Q41_16: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.16',
      },
      Q41_17: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.17',
      },
      Q41_18: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.18',
      },
      Q41_19: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.19',
      },
      Q41_20: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.20',
      },
      Q41_21: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.21',
      },
      Q41_22: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.22',
      },
      Q41_23: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.23',
      },
      Q41_24: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.24',
      },
      Q41_25: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.25',
      },
      Q41_26: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.26',
      },
      Q41_27: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.27',
      },
      Q41_28: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.28',
      },
      Q41_29: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.29',
      },
      Q41_30: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.30',
      },
      Q41_31: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.31',
      },
      Q41_32: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.32',
      },
      Q41_33: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.33',
      },
      Q41_34: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.34',
      },
      Q41_35: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.35',
      },
      Q41_36: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.36',
      },
      Q41_37: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.37',
      },
      Q41_38: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.38',
      },
      Q41_39: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.39',
      },
      Q41_40: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.40',
      },
      Q41_41: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.41',
      },
      Q41_42: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.42',
      },
      Q41_43: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.43',
      },
      Q41_44: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.44',
      },
      Q41_45: {
        question: 'QID22',
        subQuestion: 'QID22.subQuestions.45',
      },
    },
    blocks: {
      BL_cUZnumvGZa0GZIa: {
        description: 'Default Question Block',
        elements: [
          {
            type: 'Question',
            questionId: 'QID1',
          },
        ],
      },
      BL_6KbyIX0XVIgHWaq: {
        description: 'Question 1',
        elements: [
          {
            type: 'Question',
            questionId: 'QID2',
          },
          {
            type: 'Question',
            questionId: 'QID23',
          },
        ],
      },
      BL_6R3EOmxFekRGbzM: {
        description: 'Question 2',
        elements: [
          {
            type: 'Question',
            questionId: 'QID3',
          },
          {
            type: 'Question',
            questionId: 'QID25',
          },
          {
            type: 'Question',
            questionId: 'QID26',
          },
          {
            type: 'Question',
            questionId: 'QID27',
          },
          {
            type: 'Question',
            questionId: 'QID4',
          },
          {
            type: 'Question',
            questionId: 'QID28',
          },
          {
            type: 'Question',
            questionId: 'QID29',
          },
        ],
      },
      BL_e2QVkhmw1NE40se: {
        description: 'Question 3',
        elements: [
          {
            type: 'Question',
            questionId: 'QID5',
          },
          {
            type: 'Question',
            questionId: 'QID30',
          },
          {
            type: 'Question',
            questionId: 'QID31',
          },
          {
            type: 'Question',
            questionId: 'QID32',
          },
          {
            type: 'Question',
            questionId: 'QID33',
          },
          {
            type: 'Question',
            questionId: 'QID34',
          },
        ],
      },
      BL_1LbUB8RoiSDdT70: {
        description: 'Question 1',
        elements: [
          {
            type: 'Question',
            questionId: 'QID6',
          },
          {
            type: 'Question',
            questionId: 'QID35',
          },
          {
            type: 'Question',
            questionId: 'QID36',
          },
          {
            type: 'Question',
            questionId: 'QID7',
          },
        ],
      },
      BL_0ID6SQEW1A2Jmzc: {
        description: 'Question 2',
        elements: [
          {
            type: 'Question',
            questionId: 'QID8',
          },
          {
            type: 'Question',
            questionId: 'QID37',
          },
          {
            type: 'Question',
            questionId: 'QID38',
          },
          {
            type: 'Question',
            questionId: 'QID39',
          },
        ],
      },
      BL_2h5C5SIdvxAqo9U: {
        description: 'Question 3',
        elements: [
          {
            type: 'Question',
            questionId: 'QID9',
          },
          {
            type: 'Question',
            questionId: 'QID10',
          },
          {
            type: 'Question',
            questionId: 'QID11',
          },
          {
            type: 'Question',
            questionId: 'QID12',
          },
        ],
      },
      BL_3Da1zqelUz3RBl4: {
        description: 'Question 4',
        elements: [
          {
            type: 'Question',
            questionId: 'QID13',
          },
          {
            type: 'Question',
            questionId: 'QID40',
          },
          {
            type: 'Question',
            questionId: 'QID41',
          },
          {
            type: 'Question',
            questionId: 'QID14',
          },
          {
            type: 'Question',
            questionId: 'QID15',
          },
          {
            type: 'Question',
            questionId: 'QID16',
          },
        ],
      },
      BL_d42GvgAP8L6y3Xg: {
        description: 'Question 5',
        elements: [
          {
            type: 'Question',
            questionId: 'QID17',
          },
          {
            type: 'Question',
            questionId: 'QID18',
          },
          {
            type: 'Question',
            questionId: 'QID19',
          },
          {
            type: 'Question',
            questionId: 'QID42',
          },
          {
            type: 'Question',
            questionId: 'QID20',
          },
          {
            type: 'Question',
            questionId: 'QID21',
          },
          {
            type: 'Question',
            questionId: 'QID22',
          },
        ],
      },
    },
    flow: [
      {
        type: 'Branch',
        flow: [
          {
            type: 'EndSurvey',
          },
        ],
      },
      {
        type: 'EmbeddedData',
      },
      {
        type: 'WebService',
      },
      {
        id: 'BL_cUZnumvGZa0GZIa',
        type: 'Block',
      },
      {
        type: 'TableOfContents',
        flow: [
          {
            id: 'BL_6KbyIX0XVIgHWaq',
            type: 'Block',
          },
          {
            id: 'BL_6R3EOmxFekRGbzM',
            type: 'Block',
          },
          {
            id: 'BL_e2QVkhmw1NE40se',
            type: 'Block',
          },
          {
            type: 'TableOfContents',
            flow: [
              {
                id: 'BL_1LbUB8RoiSDdT70',
                type: 'Block',
              },
              {
                id: 'BL_0ID6SQEW1A2Jmzc',
                type: 'Block',
              },
              {
                id: 'BL_2h5C5SIdvxAqo9U',
                type: 'Block',
              },
            ],
          },
          {
            id: 'BL_3Da1zqelUz3RBl4',
            type: 'Block',
          },
          {
            id: 'BL_d42GvgAP8L6y3Xg',
            type: 'Block',
          },
        ],
      },
      {
        type: 'EndSurvey',
      },
    ],
    embeddedData: [
      {
        name: 'ContactEmail',
      },
      {
        name: 'Interviewer',
      },
      {
        name: 'Interviewer Email',
      },
      {
        name: 'Name',
      },
      {
        name: 'Spouse Email',
      },
      {
        name: 'Type',
      },
      {
        name: 'Store Name',
        type: 'Custom',
      },
      {
        name: 'State',
        type: 'Custom',
      },
    ],
    comments: {},
    loopAndMerge: {},
    responseCounts: {
      auditable: 1,
      generated: 5,
      deleted: 2,
    },
  },
  meta: {
    httpStatus: '200 - OK',
    requestId: 'd46be618-4a18-4057-8336-997bac4636ec',
    notice: 'Request proxied. For faster response times, use this host instead: sin1.qualtrics.com',
  },
};

const response = {
  result: {
    responseId: 'R_4q9chk4R6DUx7PS',
    values: {
      startDate: '2024-03-13T03:13:01Z',
      endDate: '2024-03-13T03:15:28Z',
      status: 1,
      progress: 100,
      duration: 146,
      finished: 1,
      recordedDate: '2024-03-13T03:15:33.506Z',
      locationLatitude: '1.385',
      locationLongitude: '103.7473',
      distributionChannel: 'preview',
      userLanguage: 'EN-GB',
      QID2: 1,
      QID2_DO: ['1', '2', '3'],
      QID23: ['1', '2'],
      QID23_DO: ['1', '2', '3'],
      QID25_TEXT: '12312',
      QID26_TEXT: '123123',
      QID27_TEXT: '123132131312',
      QID5_1: 1,
      QID5_2: 2,
      QID5_DO: ['1', '2'],
      QID30_1: 1,
      QID30_2: 2,
      QID30_3: 1,
      QID30_DO: ['1', '2', '3'],
      QID31_1_1: 1,
      QID31_1_2: 1,
      QID31_1_3: 1,
      QID31_2_1: 1,
      QID31_2_2: 1,
      QID31_2_3: 1,
      QID31_3_1: 2,
      QID31_3_2: 3,
      QID31_3_3: 4,
      QID31_DO: ['1', '2', '3'],
      QID32_1_1: 10,
      QID32_1_2: 10,
      QID32_1_3: 30,
      QID32_2_1: 10,
      QID32_2_2: 10,
      QID32_2_3: 40,
      QID32_3_1: 20,
      QID32_3_2: 20,
      QID32_3_3: 50,
      QID32_DO: ['1', '2', '3'],
      QID33_1_1: '1',
      QID33_1_2: '123',
      QID33_1_3: '123',
      QID33_2_1: '2',
      QID33_2_2: '123',
      QID33_2_3: '123',
      QID33_3_1: '23',
      QID33_3_2: '123',
      QID33_3_3: '123',
      QID33_DO: ['1', '2', '3'],
      QID34_1: 1,
      QID34_2: 2,
      QID34_DO: ['1', '2', '3'],
      QID6_1: 73,
      QID6_2: 32,
      QID6_3: 73,
      QID6_DO: ['1', '2', '3'],
      QID35_1: 49,
      QID35_2: 81,
      QID35_3: 35,
      QID35_DO: ['1', '2', '3'],
      QID36_1: 5,
      QID36_2: 5,
      QID36_3: 4,
      QID36_DO: ['1', '2', '3'],
      QID7_1: '1',
      QID7_2: '1',
      QID7_3: '34',
      QID7_DO: ['1', '2', '3'],
      QID8_1: 1,
      QID8_2: 3,
      QID8_3: 2,
      QID8_DO: ['1', '2', '3'],
      QID37_1: 1,
      QID37_2: 3,
      QID37_3: 2,
      QID37_DO: ['1', '2', '3'],
      QID38_1: 1,
      QID38_2: 2,
      QID38_3: 3,
      QID38_DO: ['1', '2', '3'],
      QID39_1: 2,
      QID39_2: 3,
      QID39_3: 1,
      QID39_DO: ['1', '2', '3'],
      'QID9#1_1': 2,
      'QID9#1_3': 1,
      'QID9#2_2': 1,
      'QID9#2_3': 2,
      QID9_DO: ['1', '2', '3'],
      QID10_NPS_GROUP: 3,
      QID10: 10,
      QID10_DO: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      QID11_FIRST_CLICK: 1.313,
      QID11_LAST_CLICK: 135.374,
      QID11_PAGE_SUBMIT: 136.079,
      QID11_CLICK_COUNT: 142,
      QID12: 5,
      QID12_DO: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      QID13_1: 10,
      QID13_2: 20,
      QID13_3: 340,
      QID13_DO: ['1', '2', '3'],
      QID40_1: 76,
      QID40_2: 34,
      QID40_3: 95,
      QID40_DO: ['1', '2', '3'],
      QID41_1: 60,
      QID41_2: 18,
      QID41_3: 90,
      QID41_DO: ['1', '2', '3'],
      QID14_FILE_ID: 'F_3RkZ4h0KlYngmaq',
      QID14_FILE_NAME: 'Sg.png',
      QID14_FILE_SIZE: 2794631,
      QID14_FILE_TYPE: 'image/png',
      QID15_0_GROUP: ['1', '3'],
      QID15_1_GROUP: ['2'],
      QID15_2_GROUP: [],
      QID15_G0_1_RANK: 1,
      QID15_G0_3_RANK: 2,
      QID15_G1_2_RANK: 1,
      QID15_DO: ['1', '2', '3'],
      QID17_FILE_ID: 'F_UWSU1yfkJTYQKyd',
      QID17_FILE_NAME: 'signature.png',
      QID17_FILE_SIZE: 10691,
      QID17_FILE_TYPE: 'image/png',
      QID18: [
        {
          x: 1386,
          y: 509,
        },
      ],
      QID18_REGIONS: ['Region #5'],
      QID20_BROWSER: 'Edge',
      QID20_VERSION: '122.0.0.0',
      QID20_OS: 'Windows NT 10.0',
      QID20_RESOLUTION: '1920x1080',
      QID22_1: ['4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17'],
      QID22_2: ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
      QID22_3: ['25', '26', '27', '28', '29', '30', '31', '32', '33'],
      QID22_DO: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
        '37',
        '38',
        '39',
        '40',
        '41',
        '42',
      ],
    },
    labels: {
      status: 'Survey Preview',
      finished: 'True',
      QID2: '1',
      QID2_DO: ['1', '2', '3'],
      QID23: ['1A', '1B'],
      QID23_DO: ['1A', '1B', '1C'],
      QID5_1: 'Click to write Scale Point 1',
      QID5_2: 'Click to write Scale Point 2',
      QID5_DO: ['Click to write Statement 1:Right', 'Click to write Statement 2:Right'],
      QID30_1: '1',
      QID30_2: '2',
      QID30_3: '1',
      QID30_DO: [
        'Click to write Statement 1:Right',
        'Click to write Statement 2:Right',
        'Click to write Statement 3:Right',
      ],
      QID31_DO: [
        'Click to write Statement 1',
        'Click to write Statement 2',
        'Click to write Statement 3',
      ],
      QID32_DO: [
        'Click to write Statement 1',
        'Click to write Statement 2',
        'Click to write Statement 3',
      ],
      QID33_DO: [
        'Click to write Statement 1',
        'Click to write Statement 2',
        'Click to write Statement 3',
      ],
      QID34_1: 'Click to write Scale Point 1',
      QID34_2: 'Click to write Scale Point 2',
      QID34_DO: [
        'Click to write Statement 1',
        'Click to write Statement 2',
        'Click to write Statement 3',
      ],
      QID6_DO: ['Click to write Choice 1', 'Click to write Choice 2', 'Click to write Choice 3'],
      QID35_DO: ['Click to write Choice 1', 'Click to write Choice 2', 'Click to write Choice 3'],
      QID36_DO: ['Click to write Choice 1', 'Click to write Choice 2', 'Click to write Choice 3'],
      QID7_DO: ['Click to write Choice 1', 'Click to write Choice 2', 'Click to write Choice 3'],
      QID8_DO: ['Click to write Item 1', 'Click to write Item 2', 'Click to write Item 3'],
      QID37_DO: ['Click to write Item 1', 'Click to write Item 2', 'Click to write Item 3'],
      QID38_DO: ['Click to write Item 1', 'Click to write Item 2', 'Click to write Item 3'],
      QID39_DO: ['Click to write Item 1', 'Click to write Item 2', 'Click to write Item 3'],
      'QID9#1_1': 'Answer 2',
      'QID9#1_3': 'Answer 1',
      'QID9#2_2': 'Answer 1',
      'QID9#2_3': 'Answer 2',
      QID9_DO: [
        'Click to write Statement 1',
        'Click to write Statement 2',
        'Click to write Statement 3',
      ],
      QID10_NPS_GROUP: 'Promoter',
      QID10_DO: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      QID12: '5',
      QID12_DO: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      QID13_DO: ['Click to write Choice 1', 'Click to write Choice 2', 'Click to write Choice 3'],
      QID40_DO: ['Click to write Choice 1', 'Click to write Choice 2', 'Click to write Choice 3'],
      QID41_DO: ['Click to write Choice 1', 'Click to write Choice 2', 'Click to write Choice 3'],
      QID15_0_GROUP: ['Click to write Item 1', 'Click to write Item 3'],
      QID15_1_GROUP: ['Click to write Item 2'],
      QID15_2_GROUP: [],
      QID15_DO: ['Click to write Item 1', 'Click to write Item 2', 'Click to write Item 3'],
      QID22_1: [
        '1: This',
        '2: is',
        '3: the',
        '4: text',
        '5: you',
        '6: can',
        '7: highlight',
        '8: with',
        '9: the',
        '10: above',
        '11: colour',
        '12: categories.',
        '13: To',
        '14: edit',
      ],
      QID22_2: [
        '31: Clicking',
        '32: directly',
        '33: on',
        '34: words',
        '35: will',
        '36: allow',
        '37: or',
        '38: disallow',
        '39: respondents',
        '40: from',
        '41: highlighting',
        '42: them.',
      ],
      QID22_3: [
        '22: Click',
        '23: between',
        '24: the',
        '25: words',
        '26: to',
        '27: combine',
        '28: or',
        '29: separate',
        '30: them.',
      ],
      QID22_DO: [
        '1: This',
        '2: is',
        '3: the',
        '4: text',
        '5: you',
        '6: can',
        '7: highlight',
        '8: with',
        '9: the',
        '10: above',
        '11: colour',
        '12: categories.',
        '13: To',
        '14: edit',
        '15: this',
        '16: text,',
        '17: click',
        '18: on',
        '19: the',
        '20: link',
        '21: below.',
        '22: Click',
        '23: between',
        '24: the',
        '25: words',
        '26: to',
        '27: combine',
        '28: or',
        '29: separate',
        '30: them.',
        '31: Clicking',
        '32: directly',
        '33: on',
        '34: words',
        '35: will',
        '36: allow',
        '37: or',
        '38: disallow',
        '39: respondents',
        '40: from',
        '41: highlighting',
        '42: them.',
      ],
    },
    displayedFields: [
      'QID15_1_GROUP',
      'QID37_1',
      'QID37_2',
      'QID37_3',
      'QID32_1_2',
      'QID18_REGIONS',
      'QID32_1_3',
      'QID11_LAST_CLICK',
      'QID32_1_1',
      'QID31_3_3',
      'QID31_3_1',
      'QID40_2',
      'QID31_3_2',
      'QID40_1',
      'QID40_3',
      'QID8_3',
      'QID20_OS',
      'QID7_1',
      'QID7_3',
      'QID7_2',
      'QID3_1',
      'QID17_FILE_TYPE',
      'QID19_7',
      'QID15_G0_1_RANK',
      'QID19_6',
      'QID33_2_2',
      'QID19_5',
      'QID33_2_3',
      'QID19_4',
      'QID19_3',
      'QID33_2_1',
      'QID19_1',
      'QID34_2',
      'QID34_3',
      'QID38_1',
      'QID38_2',
      'QID38_3',
      'QID15_G2_1_RANK',
      'QID32_2_1',
      'QID32_2_2',
      'QID15_G0_2_RANK',
      'QID32_2_3',
      'QID9#2_2',
      'QID9#2_1',
      'QID20_BROWSER',
      'QID20_RESOLUTION',
      'QID9#2_3',
      'QID41_1',
      'QID41_3',
      'QID15_0_GROUP',
      'QID41_2',
      'QID22_1',
      'QID22_2',
      'QID22_3',
      'QID14_FILE_SIZE',
      'QID15_G1_3_RANK',
      'QID8_2',
      'QID8_1',
      'QID11_FIRST_CLICK',
      'QID33_1_3',
      'QID17_FILE_SIZE',
      'QID11_CLICK_COUNT',
      'QID33_1_1',
      'QID33_1_2',
      'QID35_1',
      'QID17_FILE_NAME',
      'QID35_2',
      'QID35_3',
      'QID39_1',
      'QID31_1_1',
      'QID39_2',
      'QID31_1_2',
      'QID39_3',
      'QID32_3_1',
      'QID32_3_2',
      'QID32_3_3',
      'QID9#1_3',
      'QID9#1_2',
      'QID9#1_1',
      'QID26_TEXT',
      'QID31_1_3',
      'QID15_G2_3_RANK',
      'QID5_2',
      'QID15_G0_3_RANK',
      'QID2',
      'QID25_TEXT',
      'QID5_1',
      'QID15_G1_2_RANK',
      'QID14_FILE_TYPE',
      'QID20_VERSION',
      'QID30_1',
      'QID30_2',
      'QID30_3',
      'QID13_3',
      'QID13_2',
      'QID13_1',
      'QID34_1',
      'QID36_1',
      'QID36_2',
      'QID36_3',
      'QID18',
      'QID31_2_1',
      'QID17_FILE_ID',
      'QID10_NPS_GROUP',
      'QID12',
      'QID31_2_2',
      'QID31_2_3',
      'QID10',
      'QID6_1',
      'QID6_2',
      'QID6_3',
      'QID11_PAGE_SUBMIT',
      'QID15_2_GROUP',
      'QID14_FILE_NAME',
      'QID15_G2_2_RANK',
      'QID33_3_3',
      'QID33_3_1',
      'QID33_3_2',
      'QID15_G1_1_RANK',
      'QID14_FILE_ID',
      'QID23',
      'QID27_TEXT',
    ],
    displayedValues: {
      QID15_1_GROUP: ['1', '2', '3'],
      QID37_1: [1, 2, 3],
      QID37_2: [1, 2, 3],
      QID37_3: [1, 2, 3],
      QID18_REGIONS: ['Other', 'Other', 'Other', 'Other', 'Other', 'Other'],
      QID8_3: [1, 2, 3],
      QID19_7: ['Off', 'On'],
      QID15_G0_1_RANK: [1, 2, 3],
      QID19_6: ['Off', 'On'],
      QID19_5: ['Off', 'On'],
      QID19_4: ['Off', 'On'],
      QID19_3: ['Off', 'On'],
      QID19_1: ['Off', 'On'],
      QID34_2: [1, 2],
      QID34_3: [1, 2],
      QID38_1: [1, 2, 3],
      QID38_2: [1, 2, 3],
      QID38_3: [1, 2, 3],
      QID15_G2_1_RANK: [1, 2, 3],
      QID15_G0_2_RANK: [1, 2, 3],
      'QID9#2_2': [1, 2],
      'QID9#2_1': [1, 2],
      'QID9#2_3': [1, 2],
      QID15_0_GROUP: ['1', '2', '3'],
      QID22_1: [
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
        '37',
        '38',
        '39',
        '40',
        '41',
        '42',
        '43',
        '44',
        '45',
      ],
      QID22_2: [
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
        '37',
        '38',
        '39',
        '40',
        '41',
        '42',
        '43',
        '44',
        '45',
      ],
      QID22_3: [
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '18',
        '19',
        '20',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '28',
        '29',
        '30',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
        '37',
        '38',
        '39',
        '40',
        '41',
        '42',
        '43',
        '44',
        '45',
      ],
      QID15_G1_3_RANK: [1, 2, 3],
      QID8_2: [1, 2, 3],
      QID8_1: [1, 2, 3],
      QID39_1: [1, 2, 3],
      QID39_2: [1, 2, 3],
      QID39_3: [1, 2, 3],
      'QID9#1_3': [1, 2],
      'QID9#1_2': [1, 2],
      'QID9#1_1': [1, 2],
      QID15_G2_3_RANK: [1, 2, 3],
      QID5_2: [1, 2],
      QID15_G0_3_RANK: [1, 2, 3],
      QID2: [1, 2, 3],
      QID5_1: [1, 2],
      QID15_G1_2_RANK: [1, 2, 3],
      QID30_1: [1, 2, 3],
      QID30_2: [1, 2, 3],
      QID30_3: [1, 2, 3],
      QID34_1: [1, 2],
      QID10_NPS_GROUP: [1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 3],
      QID12: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      QID10: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      QID15_2_GROUP: ['1', '2', '3'],
      QID15_G2_2_RANK: [1, 2, 3],
      QID15_G1_1_RANK: [1, 2, 3],
      QID23: ['1', '2', '3'],
    },
  },
  meta: {
    requestId: '7ea0e3eb-8b46-4265-94ba-43be9bb48e42',
    httpStatus: '200 - OK',
    notice: 'Request proxied. For faster response times, use this host instead: sin1.qualtrics.com',
  },
};
